version: '2'
services:
  api:
    build: .
    environment:
      - "TZ=Europe/Amsterdam"
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    volumes_from:
      - gems
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
  gems:
    image: busybox
    volumes:
      - /ruby_gems
